"""Input-injection abstraction."""

from __future__ import annotations

from typing import Protocol, runtime_checkable


@runtime_checkable
class InputInjector(Protocol):
    def click(self, x: int, y: int) -> None: ...
    def right_click(self, x: int, y: int) -> None: ...
    def move_to(self, x: int, y: int) -> None: ...
    def press(self, key: str) -> None: ...
    def hotkey(self, modifiers: list[str], key: str) -> None: ...
    def drag(self, start_xy: tuple[int, int], end_xy: tuple[int, int], duration: float) -> None: ...
    def scroll(self, clicks: int, x: int | None = None, y: int | None = None) -> None: ...
